-- 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER joeun IDENTIFIED BY 123456;
ALTER USER joeun DEFAULT TABLESPACE users;
ALTER USER joeun QUOTA UNLIMITED ON users;
GRANT DBA TO joeun;